### ISSUE TITLE
App runtime issue

### ISSUE THREAD

**Issue by rubbieKelvin** [rubbieKelvin/courier#4]
i just cloned this repo, so i got this error when i run the app with `python main.py` for the second time.
```
Traceback (most recent call last):
  File "/home/rubbiekelvin/Desktop/courier/main.py", line 16, in <module>
    from lib.server import CourierServer
  File "/home/rubbiekelvin/.local/lib/python3.9/site-packages/shiboken2/files.dir/shibokensupport/__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
  File "/home/rubbiekelvin/Desktop/courier/lib/server.py", line 17, in <module>
    from .messages import Text
  File "/home/rubbiekelvin/.local/lib/python3.9/site-packages/shiboken2/files.dir/shibokensupport/__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
  File "/home/rubbiekelvin/Desktop/courier/lib/messages.py", line 98, in <module>
    class Binary(PrivateTextMessage):
  File "/home/rubbiekelvin/Desktop/courier/lib/messages.py", line 104, in Binary
    os.mkdir(root)
FileNotFoundError: [Errno 2] No such file or directory: '//.local/share/Courier'
```

**Comment by rubbieKelvin** [comment]
fixed.
